# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Güsel
email: güssl@outlook.com
description: > # this means to ignore newlines until "baseurl:"
    Güssel/Güsel/Güssl/Gösu-Band-Homepage. Grümpel Punk Band us Zug.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  mogria

# Build settings
markdown: kramdown

# Data Collections:
collections:
    songs:
        output: true
        permalink: /:collection/:path

# Jekyll Plugins
plugins:
- jekyll-livereload
- jekyll-email-protect
